# -- Site Configuration --
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://avolicious.github.io"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
