languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Avolicious's personal blog"
copyright = ":copyright: Avolicious"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
description = "My personal blog"

[params.author]
name = "Avolicious"
# image = "img/author.jpg"
headline = "I'm only human"
bio = "A little bit about you"
links = [{ email = "mailto:avolicious@kog.tw" }]
