# -- Main Menu --

[[main]]
name = "Home"
pageRef = "/"
weight = 5

[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Categories"
pageRef = "categories"
weight = 20

[[main]]
name = "GitHub"
url = "https://github.com/avolicious"
weight = 40
[main.params]
icon = "github"
showName = false
target = "_blank"

[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"

[[main]]
identifier = "locale"
weight = 100
[main.params]
action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Privacy"
pageRef = "privacy"
